spring:
  application:
    name: master-server

  docker:
    compose:
      enabled: true
      lifecycle-management: start-only
      file: docker-compose.yml

  datasource:
    url: jdbc:postgresql://localhost:5432/gamemaster
    username: gamemaster
    password: gamemaster

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  # Google Gemini AI Configuration
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
        project-id: ${GM-PROJECT}
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash
            temperature: 0.7
        embedding:
          api-key: ${GOOGLE_GENAI_API_KEY}
          options:
            model: gemini-embedding-001
    vectorstore:
      opensearch:
        uris: http://localhost:9200
        index-name: vector-store
        initialize-schema: true
        dimensions: 1536
        similarity: cosine
        use-approximate-knn: true

  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB

server:
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

game-master:
  chat:
    default-language: catalan
    default-model: gpt-4.1-mini
  transcription:
    model: whisper-1
    language: ""
  ingestion:
    enable-rate-limit: false
    rpm-limit: 90
    tpm-limit: 38000
    max-retries: 5
    chunk-size: 2000
    min-chunk-size-chars: 300
    min-chunk-length-to-embed: 50
    window-minutes: 1

logging:
  level:
    root: warn
    dev.agiro.masterserver: debug
