version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: masterdb
      POSTGRES_USER: masteruser
      POSTGRES_PASSWORD: masterpassword
    ports:
      - "35555:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d


volumes:
  db-data:
